production:
  server: "https://test-private-pub-alpha.herokuapp.com/faye"

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension.

  secret_token: 4c843fdf177182337413c16563273976d0fb1ccf1676e88edfd0f2e89a8b0b15
  signature_expiration: 3600 # one day
